/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sptech.login.java.swing;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.discos.Disco;
import java.awt.Color;
import java.net.UnknownHostException;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme.martin@VALEMOBI.CORP
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pnlGeral = new javax.swing.JPanel();
        btnFinalizar = new javax.swing.JButton();
        pnlRam = new javax.swing.JPanel();
        lblRam = new javax.swing.JLabel();
        pnlDisco = new javax.swing.JPanel();
        lblDisco = new javax.swing.JLabel();
        pnlCpu1 = new javax.swing.JPanel();
        lblCpu = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUsoDisco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuDash = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGeral.setBackground(new java.awt.Color(249, 249, 249));
        pnlGeral.setPreferredSize(new java.awt.Dimension(1218, 680));

        btnFinalizar.setBackground(new java.awt.Color(164, 22, 26));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(249, 249, 249));
        btnFinalizar.setText("Finalizar Aplicação");
        btnFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinalizarMouseExited(evt);
            }
        });
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        pnlRam.setBackground(new java.awt.Color(164, 22, 26));
        pnlRam.setPreferredSize(new java.awt.Dimension(230, 230));

        lblRam.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblRam.setForeground(new java.awt.Color(249, 249, 249));
        lblRam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRam.setText("10.00%");

        javax.swing.GroupLayout pnlRamLayout = new javax.swing.GroupLayout(pnlRam);
        pnlRam.setLayout(pnlRamLayout);
        pnlRamLayout.setHorizontalGroup(
            pnlRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRamLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRamLayout.setVerticalGroup(
            pnlRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRamLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(lblRam)
                .addGap(73, 73, 73))
        );

        pnlDisco.setBackground(new java.awt.Color(164, 22, 26));
        pnlDisco.setPreferredSize(new java.awt.Dimension(230, 230));
        pnlDisco.setLayout(new java.awt.BorderLayout());

        lblDisco.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblDisco.setForeground(new java.awt.Color(249, 249, 249));
        lblDisco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisco.setText("25.00%");
        pnlDisco.add(lblDisco, java.awt.BorderLayout.CENTER);

        pnlCpu1.setBackground(new java.awt.Color(164, 22, 26));
        pnlCpu1.setPreferredSize(new java.awt.Dimension(230, 230));

        lblCpu.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblCpu.setForeground(new java.awt.Color(249, 249, 249));
        lblCpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpu.setText("40.00%");

        javax.swing.GroupLayout pnlCpu1Layout = new javax.swing.GroupLayout(pnlCpu1);
        pnlCpu1.setLayout(pnlCpu1Layout);
        pnlCpu1Layout.setHorizontalGroup(
            pnlCpu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCpu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCpu)
                .addContainerGap())
        );
        pnlCpu1Layout.setVerticalGroup(
            pnlCpu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCpu1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblCpu)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        btnIniciar.setBackground(new java.awt.Color(25, 164, 22));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(249, 249, 249));
        btnIniciar.setText("Iniciar Aplicação");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("DISCO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("CPU");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("RAM");

        lblUsoDisco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsoDisco.setForeground(new java.awt.Color(51, 51, 51));
        lblUsoDisco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsoDisco.setText("Em Uso");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Em Uso");
        jLabel1.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Em Uso");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeralLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel4)
                .addGap(240, 240, 240)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(185, 185, 185))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGeralLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlGeralLayout.createSequentialGroup()
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlRam, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(131, 131, 131)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsoDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlDisco, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCpu1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(133, 133, 133))
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCpu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsoDisco)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(79, 79, 79)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        menu.setBackground(new java.awt.Color(164, 22, 26));
        menu.setBorder(null);
        menu.setForeground(new java.awt.Color(228, 228, 228));
        menu.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        menu.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        menu.setMinimumSize(new java.awt.Dimension(74, 70));
        menu.setPreferredSize(new java.awt.Dimension(74, 60));

        menuDash.setText("Dashboard");
        menuDash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menu.add(menuDash);

        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuSairMouseExited(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menu.add(menuSair);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarMouseEntered
        btnFinalizar.setBackground(Color.WHITE);
        btnFinalizar.setForeground(new Color(164, 22, 26));
    }//GEN-LAST:event_btnFinalizarMouseEntered

    private void btnFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarMouseExited
        btnFinalizar.setBackground(new Color(164, 22, 26));
        btnFinalizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFinalizarMouseExited

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseExited
        btnFinalizar.setBackground(new Color(164, 22, 26));
        btnFinalizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_menuSairMouseExited

    private void menuSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseEntered
        btnFinalizar.setBackground(Color.WHITE);
        btnFinalizar.setForeground(new Color(164, 22, 26));
    }//GEN-LAST:event_menuSairMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        IniciarLeitura();
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    public void IniciarLeitura() {
        int periodo = 1000;   // tempo de espera antes da 1ï¿½ execuï¿½ï¿½o da tarefa.
        int interval = 5000;  // intervalo no qual a tarefa serï¿½ executada.
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                lerDados();
            }
        }, periodo, interval);
    }

    private void lerDados() {

        Looca looca = new Looca();
        Double discoDisponivel = looca.getGrupoDeDiscos().getVolumes().stream().findAny().get().getDisponivel().doubleValue();
        Double discoTotal = looca.getGrupoDeDiscos().getVolumes().stream().findAny().get().getTotal().doubleValue();
        Double usoDisco = discoDisponivel * 100 / discoTotal;

        Double memoriaEmUso = looca.getMemoria().getEmUso().doubleValue();
        Double memoriaTotal = looca.getMemoria().getTotal().doubleValue();
        Double memoriaUsada = memoriaEmUso * 100 / memoriaTotal;

        Double usoProcessador = looca.getProcessador().getUso().doubleValue();

        lblDisco.setText(String.format("%.2f%%", usoDisco));
        lblRam.setText(String.format("%.2f%%", memoriaUsada));
        lblCpu.setText(String.format("%.2f%%", usoProcessador));
        
        Date dataHora = new Date();

        ConexaoBanco conexao = new ConexaoBanco();

//        conexao.getConexao().execute("drop table if exists tbLogs");
//
//        conexao.getConexao().execute("Create table tbLogs ("
//                + "idLog INT PRIMARY KEY AUTO_INCREMENT, "
//                + "leituraDesempenho DOUBLE,"
//                + //            "leituraTemperatura DOUBLE," +
//                //            "dataHora DATETIME," +
//                //            "fkComponente INT," +
//                //            "constraint fkComponente " +
//                //            "foreign key (fkComponente) references tbComponentes (idComponentes)" +
//                ");");
        
//        //H2
//        conexao.getConexao().update("insert into tbLogs "
//                + "values(null, ?)", usoDisco);
//        conexao.getConexao().update("insert into tbLogs "
//                + "values(null, ?)", memoriaUsada);
//        conexao.getConexao().update("insert into tbLogs "
//                + "values(null, ?)", usoProcessador);

        //AZURE
        conexao.getConexao().update("insert into tbLogs(leituraDesempenho, dataHora, fkComponente) "
                + "values(?, ?, 9)", usoDisco, dataHora);
        conexao.getConexao().update("insert into tbLogs(leituraDesempenho, dataHora, fkComponente) "
                + "values(?, ?, 10)", memoriaUsada, dataHora);
        conexao.getConexao().update("insert into tbLogs(leituraDesempenho, dataHora, fkComponente) "
                + "values(?, ?, 11)", usoProcessador, dataHora);

//        List<Map<String, Object>> tbLogs = conexao
//                .getConexao()
//                .queryForList("select * from tbLogs");
//
//        System.out.println(tbLogs);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblCpu;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblRam;
    private javax.swing.JLabel lblUsoDisco;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuDash;
    private javax.swing.JMenu menuSair;
    private javax.swing.JPanel pnlCpu1;
    private javax.swing.JPanel pnlDisco;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlRam;
    // End of variables declaration//GEN-END:variables
}
